version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379